---
title: "Analyses basées sur les cutoffs du PPS"
author: "Joël Gagnon, Ph.D."
date: "09/09/2021"
output: 
  html_document:
    toc: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

<br>
<br>

# Exploratory comparisons between groups 

<br>

```{r library}
library(tidyverse)
library(ggplot2)
```
<br>

```{r import data}
load(file = "totscores_w_cluster.Rda")
```
<br>

```{r data wrangling}

totscores_mod <- noout_dat %>% 
    mutate(cluster_res.hk = factor(cluster_res.hk,
                            labels = c("1", "2"))) %>% 
    mutate(proc_ouv = factor(proc_ouvert,
                             labels = c("À diminué",
                                        "Demeuré le même",
                                        "Empiré beaucoup",
                                        "Empiré quelque peu")))

### Create group variable based on cutoffs

totscores_mod <- totscores_mod %>% 
    mutate(pps_cutoffs = dplyr::case_when(
        pps_tot <= 27 ~ "low", 
        (pps_tot > 27 & pps_tot <= 39) ~ "medium",
        (pps_tot > 39) ~ "high")) 

totscores_mod <- totscores_mod %>% 
    mutate(pps_cutoffs = factor(pps_cutoffs,
                                levels = c("low", "medium", "high")))

```
<br>
<br>

## Visualize differences based on clustering variable

```{r plot}
totscores_mod %>% 
    ggplot(aes(proc_ouv, fill = pps_cutoffs)) +
    geom_histogram(stat = "count", binwidth = .5, alpha = .5) +
    facet_wrap(~pps_cutoffs, ncol = 1) +
    theme(axis.text.x = element_text(angle = 90))


```
<br>
<br>

## Exploratory analyses : mean differences
<br>

```{r import_lib3}
library(rstatix)
```


```{r mean_sd}

totscores_mod %>%
    anova_test(mpfi_tot ~ pps_cutoffs)

totscores_mod %>%
    anova_test(gses_tot ~ pps_cutoffs)

totscores_mod %>%
    anova_test(qmes_eng_opt ~ pps_cutoffs)

totscores_mod %>%
    anova_test(qmes_sur_eng_scol ~ pps_cutoffs)

totscores_mod %>%
    anova_test(qmes_sous_eng_scol ~ pps_cutoffs)

totscores_mod %>%
    anova_test(ese_tot ~ pps_cutoffs)

totscores_mod %>% 
    anova_test(qpr_pp ~ pps_cutoffs)

totscores_mod %>% 
    anova_test(qpr_rhs ~ pps_cutoffs)

totscores_mod %>% 
    group_by(pps_cutoffs) %>% 
    get_summary_stats(qpr_rhs)
```

## Exploratory analyses : chi-square

```{r chi_square}

cont_table <- table(totscores_mod$proc_ouv, totscores_mod$pps_cutoffs)

cont_table

chisq.test(totscores_mod$proc_ouv, totscores_mod$pps_cutoffs)
```